### ISSUE TITLE
implicit dependency on pybind11

### ISSUE THREAD

**Issue by avidale** [anyks/asc#1]
When trying to install the Pyhton version (with `pip install anyks-sc`), I run onto the following error:

```
Collecting anyks-sc
  Downloading anyks-sc-1.2.4.tar.gz (549 kB)
     |████████████████████████████████| 549 kB 1.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/dale/p3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d20041xb/anyks-sc_ea24e87779224313b08ac1dc45c32e3a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d20041xb/anyks-sc_ea24e87779224313b08ac1dc45c32e3a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5_tv200w
         cwd: /tmp/pip-install-d20041xb/anyks-sc_ea24e87779224313b08ac1dc45c32e3a/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d20041xb/anyks-sc_ea24e87779224313b08ac1dc45c32e3a/setup.py", line 6, in <module>
        import pybind11
    ModuleNotFoundError: No module named 'pybind11'
````

Apparently, `pybind11` should be included as a Python dependency.

**Comment by anyks** [comment]
python3 -m pip install pybind11

**Comment by avidale** [comment]
It's obvious that pybind11 should be installed. But why don't you include it into setup.py as a dependency, to be installed automatically?

**Comment by anyks** [comment]
Automatic installation will not come without pybind11
