### ISSUE TITLE
cannot install the project on windows: an encoding problem

### ISSUE THREAD

**Issue by avidale** [anyks/asc#3]
When I try to install the python version of the project on Windows 10 and Python 3.9.6, I run into the following error:

```
C:\Users\david>pip install anyks-sc
Collecting anyks-sc
  Using cached anyks-sc-1.2.4.tar.gz (549 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\david\appdata\local\programs\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\david\\AppData\\Local\\Temp\\pip-install-i93g79m6\\anyks-sc_0d79c8a2239c4f54a0ea206090b228bd\\setup.py'"'"'; __file__='"'"'C:\\Users\\david\\AppData\\Local\\Temp\\pip-install-i93g79m6\\anyks-sc_0d79c8a2239c4f54a0ea206090b228bd\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\david\AppData\Local\Temp\pip-pip-egg-info-j03wzy3a'
         cwd: C:\Users\david\AppData\Local\Temp\pip-install-i93g79m6\anyks-sc_0d79c8a2239c4f54a0ea206090b228bd\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\david\AppData\Local\Temp\pip-install-i93g79m6\anyks-sc_0d79c8a2239c4f54a0ea206090b228bd\setup.py", line 11, in <module>
        description = fh.read()
      File "c:\users\david\appdata\local\programs\python\python39\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 7669: character maps to <undefined>
```

I don't even know how to approach it.

**Comment by anyks** [comment]
Windows operating system is not supported
